
name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:

  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Linter
        run: flake8 .
        # Flake8 will automatically detect .flake8 at repo root

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run Linter
        run: |
          if [ -d "./server/database" ]; then
            jshint ./server/database/**/*.js
            echo "Linted all the js files successfully"
          else
            echo "No JS files found, skipping JS lint"
          fi
